/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hong_ndklibrary_NDKString */

#ifndef _Included_com_hong_ndklibrary_NDKString
#define _Included_com_hong_ndklibrary_NDKString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hong_ndklibrary_NDKString
 * Method:    getFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hong_ndklibrary_NDKString_getFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_hong_ndklibrary_NDKString
 * Method:    uploadFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_hong_ndklibrary_NDKString_uploadFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_hong_ndklibrary_NDKString
 * Method:    updateIntArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_hong_ndklibrary_NDKString_updateIntArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
